version: "3.8"

networks:
  rede:
    driver: bridge

services:
  node:
    build:
      context: ./api
      target: DEV
    container_name: api-petshop
    volumes:
      - ./api:/app
    ports:
      - 3000:3000
    networks:
      - rede

  postgres:
    image: postgres
    container_name: db-petshop
    ports:
      - 5432:5432
    volumes:
      - .docker/pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=petshop
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - rede
